manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/luigi311
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: tidbit_19key
      import: app/west.yml
  self:
    path: config
